---
sidebar: sidebar 
permalink: create-knowledgebase.html 
keywords: ai, chatbot, creating, knowledge base 
summary: AI 인프라를 구축하고 FSx for ONTAP 데이터 저장소의 기술 자료에 통합할 데이터 소스를 식별한 후에는 워크로드 팩토리를 사용하여 기술 자료를 구축할 준비가 된 것입니다. 이 단계에서는 AI 특성을 정의하고 대화를 시작하는 방안을 마련합니다. 
---
= 기술 문서를 작성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
AI 인프라를 구축하고 FSx for ONTAP 데이터 저장소의 기술 자료에 통합할 데이터 소스를 식별한 후에는 워크로드 팩토리를 사용하여 기술 자료를 구축할 준비가 된 것입니다. 이 단계의 일환으로 AI 특성을 정의하고 대화를 시작하는 방안을 마련합니다.

.이 작업에 대해
Knowledge Base에는 두 가지 데이터 통합 Modality(_public mode_와_Enterprise mode_가 있습니다.

공개 모드:: 조직의 데이터 원본을 통합하지 않고도 기술 문서를 사용할 수 있습니다. 이 경우 기술 문서에 통합된 응용 프로그램은 인터넷에 공개된 정보의 결과만 제공합니다. 이를 _public mode_integration 이라고 합니다.
엔터프라이즈 모드:: 대부분의 경우 조직의 데이터 원본을 기술 자료에 통합할 수 있습니다. 이를 엔터프라이즈 모드_통합이라고 하며, 이는 기업으로부터 지식을 제공하기 때문입니다.
+
--
조직의 데이터 원본에는 개인 ID 정보(PII)가 포함될 수 있습니다. 이러한 중요한 정보를 보호하기 위해 기술 자료를 만들고 구성할 때 _data guardrails_를 활성화할 수 있습니다. BlueXP  분류를 기반으로 하는 데이터 가드레일은 PII를 식별하고 마스킹하므로 액세스 및 복구가 불가능합니다.

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 분류에 대해 알아보십시오"^]..


NOTE: 데이터 가드레일은 언제든지 활성화 또는 비활성화할 수 있습니다. 데이터 가드레일 사용을 전환하면 Workload Factory에서 전체 기술 자료를 처음부터 검사하여 비용이 발생합니다.

--




== 기술 문서를 만들고 구성합니다

기술 자료에서는 지식 기반을 생성하는 데 사용할 Bedrock AI 모델 및 내장 형식과 같은 특성을 정의합니다.

.단계
. 중 하나를 사용하여 워크로드 팩토리에 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. AI 워크로드 타일에서 * 배포 및 관리 * 를 선택합니다.
. Knowledge Base 탭에서 * Add Knowledge Base * 를 선택합니다.
. 기술 문서 정의 페이지에서 기술 문서 설정을 구성합니다.
+
.. * 이름 *: 기술 문서에 사용할 이름을 입력하십시오.
.. *Description*: 기술 문서에 대한 자세한 설명을 입력합니다.
.. * 포함 모델 * : 포함 모델은 귀하의 데이터가 기술 자료를 위한 벡터 임베딩으로 변환되는 방법을 정의합니다. 워크로드 팩토리에서는 다음 모델을 지원합니다.
+
*** Titan Embeddings G1 - 텍스트
*** Titan Embedding Text v2
*** 타이탄 다중 모드 포함 G1
+
아마존 Bedrock에서 임베딩 모델을 이미 활성화했어야 합니다.

+
https://aws.amazon.com/bedrock/titan/["Amazon Titan에 대해 자세히 알아보십시오"^]



.. * 채팅 모델 * : 아마존 Bedrock에 통합된 Claude 채팅 모델 중에서 선택하십시오. 아마존 Bedrock에서 채팅 모델을 이미 활성화했어야 합니다.
+
선택 시 사용할 수 있는 모델에 대해 자세히 알아보십시오. https://aws.amazon.com/bedrock/claude/["아마존 Bedrock에 있는 Anthropic's Claude"^]

.. * 데이터 가드레일 * : 데이터 가드레일을 활성화 또는 비활성화할지 선택합니다. link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP  분류를 기반으로 하는 데이터 가드레일에 대해 알아보십시오"^]..
+
데이터 가드레일을 사용하려면 다음 사전 요구 사항을 완료해야 합니다.

+
*** BlueXP  분류와 통신하려면 서비스 계정이 필요합니다. 서비스 계정을 생성하려면 BlueXP  Tenancy 계정에 _Organization admin_역할이 있어야 합니다. 조직 관리자 역할을 가진 구성원은 BlueXP 의 모든 작업을 완료할 수 있습니다. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["BlueXP 에서 구성원에 역할을 추가하는 방법에 대해 알아봅니다"^]
*** AI 엔진이 에 액세스할 수 있어야 합니다 link:https://console.bluexp.netapp.com/["BlueXP 콘솔"^]
*** 에 설명된 대로 다음을 수행해야 link:https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html#quick-start["BlueXP 분류 문서"^]합니다.
+
.... BlueXP Connector를 생성합니다
.... 환경이 사전 요구 사항을 충족할 수 있는지 확인합니다
.... BlueXP 분류를 배포합니다




.. * Conversation Starters *: 이 기술 자료를 사용하는 챗봇과 상호 작용하는 사용자에게 표시되는 최대 4개의 대화 시작 프롬프트를 제공할지 여부를 선택합니다. 이 설정을 사용하는 것이 좋습니다.
+
대화 시작점을 활성화하면 기본적으로 "자동 모드"가 선택됩니다. "수동 모드"는 기술 문서에 데이터 원본을 추가한 후에만 활성화할 수 있습니다. link:manage-knowledgebase.html["기술 문서 설정을 수정하는 방법에 대해 알아봅니다"]..

.. * FSx for ONTAP 파일 시스템 *: 새로운 기술 자료를 정의하면 워크로드 공장에서 이를 저장할 새로운 Amazon FSx for NetApp ONTAP 볼륨을 생성합니다. 새 볼륨을 생성할 기존 파일 시스템 이름과 SVM(스토리지 VM이라고도 함)을 선택합니다.
.. * Snapshot policy *: 워크로드 공장 저장소 인벤토리에 정의된 기존 정책 목록에서 스냅샷 정책을 선택합니다. 선택한 스냅샷 정책에 따라 기술 자료의 반복적인 스냅샷이 자동으로 생성됩니다.
+
필요한 스냅샷 정책이 없는 경우 https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["스냅샷 정책을 생성합니다"] 볼륨이 포함된 스토리지 VM에서 수행할 수 있습니다.



. GenAI에 기술 문서를 추가하려면 * 기술 문서 만들기 * 를 선택하십시오.
+
기술 문서가 작성되는 동안 진행률 표시기가 나타납니다.

+
기술 문서를 만든 후에는 데이터 원본을 새 기술 문서에 추가하거나 데이터 원본을 추가하지 않고 프로세스를 종료할 수 있습니다. 지금 * 데이터 원본 추가 * 를 선택하고 하나 이상의 데이터 원본을 추가하는 것이 좋습니다.





== 기술 문서에 데이터 원본을 추가합니다

하나 이상의 데이터 원본을 추가하여 조직의 데이터로 기술 문서를 채울 수 있습니다.

.이 작업에 대해
지원되는 최대 데이터 원본 수는 10개입니다.

.단계
. 데이터 원본 추가 * 를 선택하면 * 파일 시스템 선택 * 페이지가 표시됩니다.
. * 파일 시스템 선택 *: 데이터 소스 파일이 있는 FSx for ONTAP 파일 시스템을 선택하고 * 다음 * 을 선택합니다.
. * 볼륨 선택 *: 데이터 원본 파일이 있는 볼륨을 선택하고 * 다음 * 을 선택합니다.
+
SMB 프로토콜을 사용하여 저장된 파일을 선택할 때 도메인, IP 주소, 사용자 이름 및 암호를 포함한 Active Directory 정보를 입력해야 합니다.

. * 데이터 소스 선택 *: 파일을 저장한 위치를 기준으로 데이터 소스 위치를 선택합니다. 전체 볼륨일 수도 있고 볼륨의 특정 폴더 또는 하위 폴더일 수도 있고 * 다음 * 을 선택합니다.
. * AI 매개 변수 정의 *: * 청크 전략 * 섹션에서 데이터 소스가 기술 문서에 통합될 때 GenAI 엔진이 데이터 소스 콘텐츠를 청크로 분할하는 방법을 정의합니다. 다음 전략 중 하나를 선택할 수 있습니다.
+
** * 다중 문장 청킹 *: 데이터 소스의 정보를 문장 정의 청크로 정리합니다. 각 청크를 구성하는 문장의 수(최대 100개)를 선택할 수 있습니다.
** * 오버랩 기반 청크 *: 데이터 소스의 정보를 인접 청크와 겹칠 수 있는 문자 정의 청크로 구성합니다. 각 청크의 크기를 문자 단위로 선택하고 각 청크가 인접한 청크와 겹치는 정도를 선택할 수 있습니다. 청크 크기는 50자에서 3000자 사이이고 겹치는 비율은 1 ~ 99%로 구성할 수 있습니다.
+

NOTE: 높은 중복 비율을 선택하면 검색 정확도가 약간 개선되어 저장소 요구 사항이 크게 증가할 수 있습니다.



. 선택한 데이터 소스가 SMB 프로토콜을 사용하는 볼륨에 있을 때만 사용할 수 있는 * 권한 인식 * 섹션에서 선택 항목을 활성화하거나 비활성화할 수 있습니다.
+
** *사용*: 이 기술 자료에 액세스하는 챗봇 사용자는 액세스 권한이 있는 데이터 원본에서 쿼리에 대한 응답만 받습니다.
** * 사용 안 함 * : 챗봇 사용자는 모든 통합 데이터 소스의 콘텐츠를 사용하여 응답을 받습니다.


. 이 데이터 소스를 기술 문서에 추가하려면 * 추가 * 를 선택하십시오.


.결과
데이터 원본이 기술 문서에 포함되기 시작합니다. 데이터 원본이 완전히 포함되면 상태가 "포함"에서 "포함"으로 변경됩니다.

기술 자료에 단일 데이터 소스를 추가한 후 챗봇 시뮬레이터 창에서 로컬로 테스트하고 필요에 따라 변경한 후 사용자가 챗봇을 사용할 수 있도록 할 수 있습니다. 또한 동일한 단계에 따라 기술 문서에 데이터 원본을 추가할 수도 있습니다.
