---
sidebar: sidebar 
permalink: identify-data-sources.html 
keywords: data sources, chatbot, documents, knowledge base 
summary: '기술 자료에 통합할 FSx for ONTAP 파일 시스템에 있는 문서(데이터 소스)를 식별하거나 생성합니다. 이러한 데이터 원본을 사용하면 기술 문서에서 조직과 관련된 데이터를 기반으로 사용자 쿼리에 대한 정확하고 개인화된 답변을 제공할 수 있습니다.' 
---
= GenAI 기술 자료에 통합할 데이터 소스를 식별합니다
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
기술 자료에 통합할 FSx for ONTAP 파일 시스템에 있는 문서(데이터 소스)를 식별하거나 생성합니다. 이러한 데이터 원본을 사용하면 기술 문서에서 조직과 관련된 데이터를 기반으로 사용자 쿼리에 대한 정확하고 개인화된 답변을 제공할 수 있습니다.



== 최대 데이터 원본 수입니다

지원되는 최대 데이터 원본 수는 10개입니다.



== 데이터 소스의 위치입니다

데이터 소스는 Amazon FSx for NetApp ONTAP 파일 시스템의 SMB 공유 또는 NFS 내보내기의 단일 볼륨 또는 볼륨 내의 폴더에 저장될 수 있습니다. 데이터 소스는 NetApp SnapMirror 데이터 보호 관계에 있는 Amazon FSx for NetApp ONTAP 볼륨에 저장할 수도 있습니다.

볼륨이나 폴더 내에서 개별 문서를 선택할 수 없으므로 데이터 원본이 포함된 각 볼륨이나 폴더에 기술 문서와 통합되지 않아야 하는 관련 문서가 포함되어 있지 않은지 확인해야 합니다.

각 기술 자료에 여러 데이터 소스를 추가할 수 있지만, 모두 AWS 계정에서 액세스할 수 있는 FSx for ONTAP 파일 시스템에 상주해야 합니다.

각 데이터 원본의 최대 파일 크기는 50MB입니다.



== 지원되는 프로토콜

기술 자료에서는 NFS 또는 SMB/CIFS 프로토콜을 사용하는 볼륨의 데이터를 지원합니다. SMB 프로토콜을 사용하여 저장된 파일을 선택할 때 기술 문서에서 해당 볼륨의 파일에 액세스할 수 있도록 Active Directory 정보를 입력해야 합니다. 여기에는 Active Directory 도메인, IP 주소, 사용자 이름 및 암호가 포함됩니다.

SMB를 통해 액세스되는 공유(파일 또는 디렉토리)에 데이터 소스를 저장하는 경우, 해당 공유에 액세스할 수 있는 권한이 있는 챗봇 사용자 또는 그룹만 데이터에 액세스할 수 있습니다. 이 "권한 인식 기능"이 활성화되면 AI 시스템은 auth0의 사용자 이메일을 SMB 공유에서 파일을 보거나 사용할 수 있는 사용자와 비교합니다. 챗봇은 포함된 파일에 대한 사용자 권한을 기반으로 해답을 제공합니다.

예를 들어, 기술 자료에 10개의 파일(데이터 소스)을 통합했고 이 중 2개의 파일이 제한된 정보를 포함하는 인적 리소스 파일인 경우, 이 두 파일에 액세스할 수 있도록 인증된 챗봇 사용자만 이러한 파일의 데이터를 포함하는 응답을 받게 됩니다.



== 지원되는 데이터 소스 파일 형식

현재 지원되는 데이터 원본 파일 형식은 다음과 같습니다.

[cols="2*"]
|===
| 파일 형식 | 연장 


| 아파치 파케 | 마루 


| 쉼표로 구분된 값 파일입니다 | .csv입니다 


| Graphics Interchange Format(그래픽 교환 형식) | gif 


| JPEG를 선택합니다 | .jpg or.jpeg 을 참조하십시오 


| 마크다운 | 진료 부서 


| Microsoft Word를 | .doc 또는 .docx 


| 일반 텍스트 | .txt입니다 


| 휴대용 문서 형식 | PDF로 이동합니다 


| 휴대용 네트워크 그래픽 | png입니다 


| WebP 이미지 | 웹 
|===