---
sidebar: sidebar 
permalink: connector/define-connector.html 
keywords: ai, chatbot, connector, 
summary: AI 인프라를 구축하고 Amazon Q Business와 통합할 데이터 소스를 식별한 후에는 커넥터를 정의할 수 있습니다. 
---
= Amazon Q Business용 NetApp 커넥터 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI 인프라를 배포하고 FSx for ONTAP 데이터 저장소에서 사용할 데이터 소스를 식별한 후 Amazon Q Business용 NetApp 커넥터를 정의할 준비가 되었습니다.

계속하기 전에 사용자의 환경이 아마존 Q 비즈니스를 위한 을 충족하는지 link:requirements-connector.html["요구 사항"]확인하십시오.

.이 작업에 대해
조직의 데이터 원본에는 PII(개인 식별 정보)가 포함될 수 있습니다. 이 중요한 정보를 보호하기 위해 커넥터를 정의할 때 _data guardrails_를 활성화할 수 있습니다. BlueXP  분류를 기반으로 하는 데이터 가드레일은 PII를 식별하고 마스킹하므로 액세스 및 복구가 불가능합니다.

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 분류에 대해 알아보십시오"^]..


NOTE: GenAI용 BlueXP  워크로드 공장은 민감한 개인 정보(SPII)를 마스킹하지 않습니다. 이 데이터 유형에 대한 자세한 내용은 을 link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-data["중요한 개인 데이터의 유형"^]참조하십시오.


NOTE: 데이터 가드레일은 언제든지 활성화 또는 비활성화할 수 있습니다. 데이터 가드레일 사용을 전환하면 워크로드 공장 출하 시 전체 데이터 소스를 처음부터 검사하여 비용이 발생할 수 있습니다.



== 커넥터를 정의합니다

Amazon Q Business용 NetApp 커넥터를 생성하세요. 이 커넥터는 GenAI와 Amazon Q Business 간의 API 및 데이터 소스 통신을 지원합니다.

.단계
. 중 하나를 사용하여 워크로드 팩토리에 link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["콘솔 환경"^]로그인합니다.
. AI 워크로드 타일에서 * 배포 및 관리 * 를 선택합니다.
. Knowledge Base & Connectors 탭에서 * Create New * 드롭다운을 선택하고 * Amazon Q Business Connector * 를 선택합니다.
. 커넥터 정의 페이지에서 커넥터 설정을 구성합니다.
+
.. * 이름 *: 연결선에 사용할 이름을 입력합니다.
.. * 설명 *: 커넥터에 대한 자세한 설명을 입력합니다.
.. * Amazon Q *: 통합하려는 Amazon Q Business 인스턴스의 지역 및 응용 프로그램 이름입니다.
.. * 데이터 가드레일 * : 데이터 가드레일을 활성화 또는 비활성화할지 선택합니다. link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP  분류를 기반으로 하는 데이터 가드레일에 대해 알아보십시오"^]..
+
데이터 가드레일을 사용하려면 다음 사전 요구 사항을 충족해야 합니다.

+
*** BlueXP  분류와 통신하려면 서비스 계정이 필요합니다. 서비스 계정을 생성하려면 BlueXP  Tenancy 계정에 _Organization admin_역할이 있어야 합니다. 조직 관리자 역할을 가진 구성원은 BlueXP 의 모든 작업을 완료할 수 있습니다. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["BlueXP 에서 구성원에 역할을 추가하는 방법에 대해 알아봅니다"^]
*** AI 엔진이 에 액세스할 수 있어야 link:https://api.bluexp.netapp.com["BlueXP  API 끝점입니다"^]합니다.
*** 에 설명된 대로 다음을 수행해야 link:https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html#quick-start["BlueXP 분류 문서"^]합니다.
+
.... BlueXP Connector를 생성합니다
.... 환경이 사전 요구 사항을 충족할 수 있는지 확인합니다
.... BlueXP 분류를 배포합니다






+

NOTE: 데이터 가드레일 기능을 활성화하면 GenAI는 일반 텍스트(포함된 이미지 또는 미디어 텍스트 제외)만 수집하고 개인 또는 중요 데이터를 마스킹하여 .txt, .md, .csv, .docx 및 .pdf 파일을 처리합니다. 다른 모든 파일 형식은 개인 또는 중요 데이터를 마스킹하지 않고 정상적으로 처리됩니다.

+
.. *FSx for ONTAP 파일 시스템*: Amazon Q Business에 대한 새로운 NetApp 커넥터를 정의하면 워크로드 팩토리는 커넥터 정보를 저장하기 위해 새로운 Amazon FSx for NetApp ONTAP 볼륨을 생성합니다. 새 볼륨을 생성할 기존 파일 시스템 및 SVM(스토리지 VM이라고도 함)을 선택합니다.
.. * Snapshot policy *: 워크로드 공장 저장소 인벤토리에 정의된 기존 정책 목록에서 스냅샷 정책을 선택합니다. GenAI는 선택한 스냅샷 정책에 따라 커넥터 정보를 주파수 단위로 저장하는 볼륨의 반복 스냅샷을 자동으로 생성합니다.
+
필요한 스냅샷 정책이 없는 경우 https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["스냅샷 정책을 생성합니다"^] 볼륨이 포함된 스토리지 VM에서 수행할 수 있습니다.



. Amazon Q Business를 GenAI와 통합하려면 * Create Connector * 를 선택하십시오.
+
커넥터가 만들어지는 동안 진행 표시기가 나타납니다.

+
커넥터가 만들어지면 데이터 원본을 커넥터에 추가하여 Amazon Q Business에서 데이터를 수집하여 인덱스에 추가할 수 있습니다. 지금 * 데이터 원본 추가 * 를 선택하고 하나 이상의 데이터 원본을 추가하는 것이 좋습니다.





== 데이터 원본을 커넥터에 추가합니다

하나 이상의 데이터 원본을 추가하여 Amazon Q Business 인덱스를 조직의 데이터로 채울 수 있습니다.

.이 작업에 대해
* 지원되는 최대 데이터 원본 수는 10개입니다.
* 아마존 Q 비즈니스 지수의 특정 서비스 제한 사항은 을 https://docs.aws.amazon.com/kendra/latest/dg/quotas.html["아마존 Q 비즈니스 문서"^] 참조하십시오.


.단계
. *데이터 소스 추가*를 선택하면 *파일 시스템 선택* 페이지가 나타납니다.
. * 파일 시스템 선택 *: 데이터 소스 파일이 있는 FSx for ONTAP 파일 시스템을 선택하고 * 다음 * 을 선택합니다.
. * 볼륨 선택 *: 데이터 원본 파일이 있는 볼륨을 선택하고 * 다음 * 을 선택합니다.
+
SMB 프로토콜을 사용하여 저장된 파일을 선택할 때 도메인, IP 주소, 사용자 이름 및 암호를 포함한 Active Directory 정보를 입력해야 합니다.

. * 데이터 소스 선택 *: 파일을 저장한 위치를 기준으로 데이터 소스 위치를 선택합니다. 전체 볼륨일 수도 있고 볼륨의 특정 폴더 또는 하위 폴더일 수도 있고 * 다음 * 을 선택합니다.
. * 구성 *: 데이터 소스가 파일에서 정보를 수집하는 방법과 검색에 포함할 파일을 구성합니다.
+
** * 파일 필터링 *: 검색에 포함할 파일을 구성합니다.
+
*** 파일 형식 지원 * 섹션에서 모든 파일 형식을 포함하거나 데이터 원본 검색에 포함할 개별 파일 형식을 선택합니다.
*** 파일 수정 시간 필터 * 섹션에서 수정 시간에 따라 파일 포함을 활성화 또는 비활성화하도록 선택합니다. 수정 시간 필터링을 사용하는 경우 목록에서 날짜 범위를 선택합니다.
+

NOTE: 수정 날짜 범위를 기준으로 파일을 포함하는 경우 날짜 범위가 충족되지 않으면(지정한 날짜 범위 내에서 파일이 수정되지 않음) 파일이 정기 검색에서 제외되고 데이터 원본에 이러한 파일이 포함되지 않습니다.





. 선택한 데이터 원본이 SMB 프로토콜을 사용하는 볼륨에 있을 때만 사용할 수 있는 * 권한 인식 * 섹션에서 권한 인식 응답을 활성화하거나 비활성화할 수 있습니다.
+
** * 활성화됨 *: 이 커넥터에 액세스하는 챗봇 사용자는 액세스 권한이 있는 데이터 원본에서 쿼리에 대한 응답만 받습니다.
** * 사용 안 함 * : 챗봇 사용자는 모든 통합 데이터 소스의 콘텐츠를 사용하여 응답을 받습니다.
+

NOTE: Active Directory 그룹 권한은 Amazon Q Business 커넥터 데이터 원본에 대해 지원되지 않습니다.



. 이 데이터 소스를 아마존 Q 비즈니스 커넥터에 추가하려면 * 추가 * 를 선택하십시오.


.결과
데이터 원본은 Amazon Q Business 인덱스에 포함됩니다. 데이터 원본이 완전히 포함되면 상태가 "포함"에서 "포함"으로 변경됩니다.

커넥터에 단일 데이터 소스를 추가한 후 Amazon Q Business 챗봇 환경에서 테스트하고 필요한 사항을 변경한 후 사용자에게 서비스를 제공할 수 있습니다. 또한 같은 단계를 수행하여 데이터 원본을 커넥터에 추가할 수도 있습니다.
